### PR TITLE
add MaterialDesign as submodule and add empty folder for icons to pre…

### LINKED ISSUE #3: Embed MDI repository
Have the MDI icons as a submodule.

### PR DESCRIPTION
**Pull request by mueller-ma**
…vent python expections

This PR creates folder that will stay empty on github

Kind of a fix for #6 
Fix #3

### CODE REVIEW

**Comment by metbril** [comment]
Awesome.

Question. I do not have in depth knowledge of git. Since I'd like to try your changes locally, how can I pull your PR into it's own branch?

**Comment by mueller-ma** [comment]
git remote add mueller-ma https://github.com/mueller-ma/openhab-mdi
git fetch mueller-ma
git checkout mueller-ma/master
git submodule update

Than you should have my master branch as local branch with the mdi as git module

**Comment by mueller-ma** [comment]
Hey @metbril 
Did you have some time to look into this?

**Comment by mueller-ma** [comment]
This PR was made from my master. I want to get some things done, but making a PR for every change really slows the development, so I merged everything in my master and try to fix the current issues. After that I can make one big PR, so all changes are in your repo. Does that sound good to you?

**Comment by metbril** [comment]
You are the first one ever to submit a pr to one of my repos. I'm a got novice so I will have a look at it, since I did some work myself that has not yet been pushed.

**Pull request closed without merging**
